org: allocations
app: core
service: entity-service
frameworkVersion: "2"

plugins:
  - serverless-plugin-monorepo
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin
  - "@allocations/serverless-allocations-redtail"

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/allocations_build_api/${opt:stage}}
  redtail:
    config: ${file(./redtail.json)}
  serverless-offline:
    httpPort: 8000
    APP_SECRET: ${APP_SECRET}
    ALLOCATIONS_TOKEN: ${ALLOCATIONS_TOKEN}
    ALLOCATIONS_ENTITY_SERVICE: ${ALLOCATIONS_ENTITY_SERVICE}
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  endpointType: PRIVATE
  vpcEndpointIds:
    - vpce-0cc4064fecca36cab
  vpc:
    securityGroupIds:
      - sg-0245432c2213eeeb8
      - sg-0665e26c1dc22d6dd
    subnetIds:
      - subnet-016539b44e6b89113
      - subnet-01a39dab42b630de6
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 512
  environment:
    APP_SECRET: ${self:custom.secrets.APP_SECRET}
    MONGODB_URI: ${self:custom.secrets.MONGODB_URI}
    DOCSPRING_TOKEN_ID: ${self:custom.secrets.ORGANIZATION_DOCSPRING_TOKEN_ID}
    DOCSPRING_TOKEN_SECRET: ${self:custom.secrets.ORGANIZATION_DOCSPRING_TOKEN_SECRET}
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*
        Condition:
          StringEquals:
            aws:SourceVpc: vpc-0d05ab0d45d1ddbd5

functions:
  initialize:
    handler: service/initialize.handler
    events:
      - sns:
          arn: ${redtail:service_topic}
          filterPolicy:
            app: [core]
            service: [entity-service]
            event: [entity-intitialize]

  uploadAgreement:
    handler: service/generate-agreements/uploaded.handler
    events:
      - s3:
          bucket: onboarding-documents-${opt:stage, 'dev'}
          event: s3:ObjectCreated:*
          existing: true

  checkSigning:
    handler: service/agreements-pending/check.handler
    events:
      - http:
          path: agreements-pending/check
          method: POST

  complete:
    handler: service/formation-pending/complete.handler
    events:
      - http:
          path: complete
          method: POST
