org: allocations
app: automations
service: health-service
frameworkVersion: "2"

plugins:
  - serverless-plugin-monorepo
  - serverless-webpack
  - serverless-offline
  - serverless-prune-plugin

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/allocations-core/${opt:stage}}
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  endpointType: PRIVATE
  vpcEndpointIds:
    - vpce-0cc4064fecca36cab
  vpc:
    securityGroupIds:
      - sg-0245432c2213eeeb8
      - sg-0665e26c1dc22d6dd
    subnetIds:
      - subnet-016539b44e6b89113
      - subnet-01a39dab42b630de6
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 512
  environment:
    APP_SECRET: ${self:custom.secrets.APP_SECRET}
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*
        Condition:
          StringEquals:
            aws:SourceVpc: vpc-0d05ab0d45d1ddbd5

functions:
  check:
    handler: service/check.handler
    events:
      - sns:
          arn: arn:aws:sns:us-east-1:046746691294:health-alarm
