app: product
service: crypto
frameworkVersion: "2"
variablesResolutionMode: 20210326

plugins:
  - serverless-plugin-monorepo
  - serverless-webpack
  - serverless-prune-plugin
  - "@allocations/serverless-allocations-redtail"

custom:
  secrets: ${ssm:/aws/reference/secretsmanager/allocations-core/${opt:stage}}
  redtail:
    config: ${file(./redtail.json)}
  prune:
    automatic: true
    number: 3

provider:
  name: aws
  endpointType: private
  vpcEndpointIds:
    - vpce-0cc4064fecca36cab
  vpc:
    securityGroupIds:
      - sg-0245432c2213eeeb8
      - sg-0665e26c1dc22d6dd
    subnetIds:
      - subnet-016539b44e6b89113
      - subnet-01a39dab42b630de6
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  memorySize: 512
  environment:
    APP_SECRET: ${self:custom.secrets.APP_SECRET}
    MONGODB_URI: ${self:custom.secrets.MONGODB_URI}
    COINBASE_COMMERCE_WEBHOOK_SECRET: ${self:custom.secrets.COINBASE_COMMERCE_WEBHOOK_SECRET}
  apiGateway:
    resourcePolicy:
      - Effect: Allow
        Principal: "*"
        Action: execute-api:Invoke
        Resource:
          - execute-api:/*
        Condition:
          StringEquals:
            aws:SourceVpc: vpc-0d05ab0d45d1ddbd5
            
functions:
  initialize:
    handler: service/initialize.handler
    events:
      - http:
          path: initialize
          method: POST

  confirm:
    handler: service/confirm.handler
    events:
      - http:
          path: confirm
          method: POST
